<a href="https://colab.research.google.com/github/Nashra-Tazmeen/NLP/blob/main/Nlp.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import spacy
nlp=spacy.load("en_core_web_sm")
doc=nlp("Dr.strange loves pav bhaji of mumbai.Hulk loves chat of delhi")
for sentence in doc.sents:
  for word in sentence:
    print(word)


Dr.strange
loves
pav
bhaji
of
mumbai
.
Hulk
loves
chat
of
delhi


In [ ]:
import spacy
nlp=spacy.blank("en")
doc=nlp("lets go to N.Y.!")
for word in doc:
  print(word)

lets
go
to
N.Y.
!


In [ ]:
type(nlp)

spacy.lang.en.English

In [ ]:
type(doc)

spacy.tokens.doc.Doc

In [ ]:
type(word)

spacy.tokens.token.Token

In [ ]:
span=doc[1:5]
type(span)

spacy.tokens.span.Span

In [ ]:
doc=nlp("tony gave two $ to peter")


In [ ]:
token0=doc[0]
token0

tony

In [ ]:
type(token0)

spacy.tokens.token.Token

In [ ]:
dir(token0)

['_',
 '__bytes__',
 '__class__',
 '__delattr__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__le__',
 '__len__',
 '__lt__',
 '__ne__',
 '__new__',
 '__pyx_vtable__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__setattr__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 '__unicode__',
 'ancestors',
 'check_flag',
 'children',
 'cluster',
 'conjuncts',
 'dep',
 'dep_',
 'doc',
 'ent_id',
 'ent_id_',
 'ent_iob',
 'ent_iob_',
 'ent_kb_id',
 'ent_kb_id_',
 'ent_type',
 'ent_type_',
 'get_extension',
 'has_dep',
 'has_extension',
 'has_head',
 'has_morph',
 'has_vector',
 'head',
 'i',
 'idx',
 'iob_strings',
 'is_alpha',
 'is_ancestor',
 'is_ascii',
 'is_bracket',
 'is_currency',
 'is_digit',
 'is_left_punct',
 'is_lower',
 'is_oov',
 'is_punct',
 'is_quote',
 'is_right_punct',
 'is_sent_end',
 'is_sent_start',
 'is_space',
 'is_stop',
 'is_title',
 'is_upper',
 'lang',
 'lang_',
 'le

In [ ]:
token0.is_alpha

True

In [ ]:
token2=doc[2]
token2.like_num

True

In [ ]:
import spacy
nlp=spacy.load("en_core_web_sm")
nlp.pipe_names
nlp.pipeline

[('tok2vec', <spacy.pipeline.tok2vec.Tok2Vec at 0x7cc8f5f51c00>),
 ('tagger', <spacy.pipeline.tagger.Tagger at 0x7cc8f439b700>),
 ('parser', <spacy.pipeline.dep_parser.DependencyParser at 0x7cc8f32a4040>),
 ('attribute_ruler',
  <spacy.pipeline.attributeruler.AttributeRuler at 0x7cc8f34bf7c0>),
 ('lemmatizer',
  <spacy.lang.en.lemmatizer.EnglishLemmatizer at 0x7cc8f32c3040>),
 ('ner', <spacy.pipeline.ner.EntityRecognizer at 0x7cc8f3ec7f40>)]

In [ ]:
doc=nlp("i just brought a gift for 100$ and gave it to my best friend")
for token in doc:
  print(token,"|",token.pos_,"|",token.lemma_)


i | PRON | I
just | ADV | just
brought | VERB | bring
a | DET | a
gift | NOUN | gift
for | ADP | for
100 | NUM | 100
$ | NUM | $
and | CCONJ | and
gave | VERB | give
it | PRON | it
to | ADP | to
my | PRON | my
best | ADJ | good
friend | NOUN | friend


In [ ]:
import nltk
import spacy


In [ ]:
from nltk.stem import PorterStemmer
stemmer=PorterStemmer()


In [ ]:
words=['eating','dancing','cooked','slept','playing','meeting','ability']
for word in words:
  print(word,"|",stemmer.stem(word))

eating | eat
dancing | danc
cooked | cook
slept | slept
playing | play
meeting | meet
ability | abil


In [ ]:
import spacy
nlp=spacy.load("en_core_web_sm")
ar=nlp.get_pipe('attribute_ruler')
ar.add([[{"TEXT":"brah"}],[{"TEXT":"bro"}]],{"LEMMA":"brother"})
doc=nlp("eating eats ate adjustable meeting good well better bro brah")
for token in doc:
  print(token,"|",token.lemma_)



eating | eat
eats | eat
ate | eat
adjustable | adjustable
meeting | meeting
good | good
well | well
better | well
bro | brother
brah | brother


In [ ]:
import spacy
nlp=spacy.load("en_core_web_sm")


In [ ]:
doc=nlp("rani is eating biryani and also drinking thumpsup")
for token in doc:
  print(token,"|",token.pos_,"|",spacy.explain(token.pos_),"|",token.tag_,spacy.explain(token.tag_))

rani | PROPN | proper noun | NNP noun, proper singular
is | AUX | auxiliary | VBZ verb, 3rd person singular present
eating | VERB | verb | VBG verb, gerund or present participle
biryani | PROPN | proper noun | NNP noun, proper singular
and | CCONJ | coordinating conjunction | CC conjunction, coordinating
also | ADV | adverb | RB adverb
drinking | VERB | verb | VBG verb, gerund or present participle
thumpsup | NOUN | noun | NN noun, singular or mass


In [ ]:
import spacy
nlp=spacy.load("en_core_web_sm")
nlp.pipe_names
doc=nlp("tesla Inc is going to acquire twitter for better $45billion")
for ent in doc.ents:
  print(ent.text,"|",ent.label_,spacy.explain(ent.label_))





tesla Inc | ORG Companies, agencies, institutions, etc.
45billion | MONEY Monetary values, including unit


In [ ]:
nlp.pipe_labels['ner']

['CARDINAL',
 'DATE',
 'EVENT',
 'FAC',
 'GPE',
 'LANGUAGE',
 'LAW',
 'LOC',
 'MONEY',
 'NORP',
 'ORDINAL',
 'ORG',
 'PERCENT',
 'PERSON',
 'PRODUCT',
 'QUANTITY',
 'TIME',
 'WORK_OF_ART']

In [ ]:
from google.colab import drive
drive.mount('/content/gdrive')

Mounted at /content/gdrive


In [ ]:
import pandas as pd
import numpy as np


In [ ]:
df=pd.read_csv("/content/drive/MyDrive/spam.csv")

In [ ]:
df.Category.value_counts()

ham     4825
spam     747
Name: Category, dtype: int64

In [ ]:
df

Category                                            Message
0         ham  Go until jurong point, crazy.. Available only ...
1         ham                      Ok lar... Joking wif u oni...
2        spam  Free entry in 2 a wkly comp to win FA Cup fina...
3         ham  U dun say so early hor... U c already then say...
4         ham  Nah I don't think he goes to usf, he lives aro...
...       ...                                                ...
5567     spam  This is the 2nd time we have tried 2 contact u...
5568      ham               Will ü b going to esplanade fr home?
5569      ham  Pity, * was in mood for that. So...any other s...
5570      ham  The guy did some bitching but I acted like i'd...
5571      ham                         Rofl. Its true to its name

[5572 rows x 2 columns]

In [ ]:
df['spam']=df['Category'].apply(lambda x:1 if x =='spam'  else 0)

In [ ]:
df.head()

Category                                            Message  spam
0      ham  Go until jurong point, crazy.. Available only ...     0
1      ham                      Ok lar... Joking wif u oni...     0
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...     1
3      ham  U dun say so early hor... U c already then say...     0
4      ham  Nah I don't think he goes to usf, he lives aro...     0

In [ ]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(df.Message,df.spam,test_size=0.2)

In [ ]:
X_train.shape

(4457,)

In [ ]:
X_test.shape

(1115,)

In [ ]:
type(X_train)

pandas.core.series.Series

In [ ]:
X_train[:4][3714]

"If i not meeting ü all rite then i'll go home lor. If ü dun feel like comin it's ok."

In [ ]:
df

Category                                            Message  spam
0         ham  Go until jurong point, crazy.. Available only ...     0
1         ham                      Ok lar... Joking wif u oni...     0
2        spam  Free entry in 2 a wkly comp to win FA Cup fina...     1
3         ham  U dun say so early hor... U c already then say...     0
4         ham  Nah I don't think he goes to usf, he lives aro...     0
...       ...                                                ...   ...
5567     spam  This is the 2nd time we have tried 2 contact u...     1
5568      ham               Will ü b going to esplanade fr home?     0
5569      ham  Pity, * was in mood for that. So...any other s...     0
5570      ham  The guy did some bitching but I acted like i'd...     0
5571      ham                         Rofl. Its true to its name     0

[5572 rows x 3 columns]

In [ ]:
X_train[:4][3714]

"If i not meeting ü all rite then i'll go home lor. If ü dun feel like comin it's ok."

In [ ]:
from sklearn.feature_extraction.text import CountVectorizer
v= CountVectorizer()
X_train_cv=v.fit_transform(X_train)
X_train_cv


<4457x7774 sparse matrix of type '<class 'numpy.int64'>'
	with 59491 stored elements in Compressed Sparse Row format>

In [ ]:
X_train_cv.toarray()[:2]

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

In [ ]:
dir(v)

['__annotations__',
 '__class__',
 '__delattr__',
 '__dict__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getstate__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__le__',
 '__lt__',
 '__module__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__setattr__',
 '__setstate__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 '__weakref__',
 '_char_ngrams',
 '_char_wb_ngrams',
 '_check_feature_names',
 '_check_n_features',
 '_check_stop_words_consistency',
 '_check_vocabulary',
 '_count_vocab',
 '_get_param_names',
 '_get_tags',
 '_limit_features',
 '_more_tags',
 '_parameter_constraints',
 '_repr_html_',
 '_repr_html_inner',
 '_repr_mimebundle_',
 '_sort_features',
 '_stop_words_id',
 '_validate_data',
 '_validate_ngram_range',
 '_validate_params',
 '_validate_vocabulary',
 '_warn_for_unused_params',
 '_white_spaces',
 '_word_ngrams',
 'analyzer',
 'binary',
 'build_analyzer',
 'build_preprocessor',
 'bui

In [ ]:
v.get_feature_names_out()[4979]

'ola'

In [ ]:
X_train_cv.shape

(4457, 7774)

In [ ]:
dir(v)

['__annotations__',
 '__class__',
 '__delattr__',
 '__dict__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getstate__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__le__',
 '__lt__',
 '__module__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__setattr__',
 '__setstate__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 '__weakref__',
 '_char_ngrams',
 '_char_wb_ngrams',
 '_check_feature_names',
 '_check_n_features',
 '_check_stop_words_consistency',
 '_check_vocabulary',
 '_count_vocab',
 '_get_param_names',
 '_get_tags',
 '_limit_features',
 '_more_tags',
 '_parameter_constraints',
 '_repr_html_',
 '_repr_html_inner',
 '_repr_mimebundle_',
 '_sort_features',
 '_stop_words_id',
 '_validate_data',
 '_validate_ngram_range',
 '_validate_params',
 '_validate_vocabulary',
 '_warn_for_unused_params',
 '_white_spaces',
 '_word_ngrams',
 'analyzer',
 'binary',
 'build_analyzer',
 'build_preprocessor',
 'bui

In [ ]:
v.vocabulary_

In [ ]:
X_train_np=X_train_cv.toarray()
X_train_np[:2]

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

In [ ]:
X_train_np[:4]

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

In [ ]:
np.where(X_train_np[0]!=0)

(array([ 911, 1919, 2511, 2839, 3192, 3501, 3626, 3787, 4160, 4203, 4250,
        4471, 4879, 4970, 5857, 6870]),)

In [ ]:
X_train_np[:4]

(4, 7774)

In [ ]:
X_train[:4]

3714    If i not meeting ü all rite then i'll go home ...
3269    Which is why i never wanted to tell you any of...
3397    URGENT! Your Mobile number has been awarded wi...
2996    Mm not entirely sure i understood that text bu...
Name: Message, dtype: object

In [ ]:
v.get_feature_names_out().shape

(7774,)

In [ ]:
X_train[1579]

"How to Make a girl Happy? It's not at all difficult to make girls happy. U only need to be... 1. A friend 2. Companion 3. Lover 4. Chef . . .  &lt;#&gt; . Good listener  &lt;#&gt; . Organizer  &lt;#&gt; . Good boyfriend  &lt;#&gt; . Very clean  &lt;#&gt; . Sympathetic  &lt;#&gt; . Athletic  &lt;#&gt; . Warm . . .  &lt;#&gt; . Courageous  &lt;#&gt; . Determined  &lt;#&gt; . True  &lt;#&gt; . Dependable  &lt;#&gt; . Intelligent . . .  &lt;#&gt; . Psychologist  &lt;#&gt; . Pest exterminator  &lt;#&gt; . Psychiatrist  &lt;#&gt; . Healer . .  &lt;#&gt; . Stylist  &lt;#&gt; . Driver . . Aaniye pudunga venaam.."

In [ ]:
X_train[3714]

"If i not meeting ü all rite then i'll go home lor. If ü dun feel like comin it's ok."

In [ ]:
X_train_np[0][4471]

1

In [ ]:
v.get_feature_names_out()[4471]

'meeting'

In [ ]:
from sklearn .naive_bayes import MultinomialNB
model=MultinomialNB()
model.fit(X_train_cv,y_train)

MultinomialNB()

In [ ]:
X_test_cv=v.transform(X_test)

In [ ]:
from sklearn.metrics import classification_report
y_pred=model.predict(X_test_cv)
print(classification_report(y_test,y_pred))


              precision    recall  f1-score   support

           0       0.99      1.00      0.99       968
           1       0.98      0.95      0.96       147

    accuracy                           0.99      1115
   macro avg       0.99      0.97      0.98      1115
weighted avg       0.99      0.99      0.99      1115



In [ ]:
emails=['hey mohan can we have a meeting tomorrow',
        '20% discount offer just for you.Dont miss this !'
]
x=v.transform(emails)
model.predict(x)

array([0, 1])

In [ ]:
from sklearn.pipeline import Pipeline
clf=Pipeline([('vectorizer',CountVectorizer()),('nb',MultinomialNB())
])

In [ ]:
clf.fit(X_train,y_train)

Pipeline(steps=[('vectorizer', CountVectorizer()), ('nb', MultinomialNB())])

In [ ]:
y_pred=clf.predict(X_test)
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           0       0.99      1.00      0.99       968
           1       0.98      0.95      0.96       147

    accuracy                           0.99      1115
   macro avg       0.99      0.97      0.98      1115
weighted avg       0.99      0.99      0.99      1115

